version: "3"

services:
  docker-dind:
    image: docker:dind
    privileged: true
    volumes:
      - jenkins-data:/var/jenkins_home
    command: [ "dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false" ]
    ports:
      - 2375:2375
    networks:
      common:
        aliases:
          - docker
  
  jenkins-server:
    build:
      context: ./jenkins
      dockerfile: jenkins.server.Dockerfile
    restart: on-failure
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Disable setup wizard  
    ports:
      - 8080:8080   # Port to expose Jenkins UI
      - 50000:5000  # Port for commnunicating with Jenkins agent
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - common
    
networks:
  common:

volumes:
  jenkins-data:
  