node('docker') {
    /* Checkout */
    git branch: 'main',
        credentialsId: 'hainenber_personal_access_token',
        url: 'https://github.com/hainenber/hetman.git'

    /* Test */
    sh 'go test -timeout 2m -cover ./...'

    /* Build and push image with DinD */
    docker.withRegistry('http://docker-registry:5000') {
        def hetmanImage = docker.build('hetman')
        /* Push to local Registry */
        hetmanImage.push()
    }
}