jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n"
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  clouds:
    - docker:
        dockerApi:
          connectTimeout: 60
          dockerHost:
            uri: "tcp://docker:2375"
          readTimeout: 60 
        name: "docker"
        exposeDockerHost: true
        templates:
          - connector: "attach"
            dockerTemplateBase:
              image: "docker-registry:5000/jenkins-agent-for-golang"
            labelString: "docker"
            name: "jenkins-agent-for-golang"
            pullStrategy: PULL_ALWAYS
            pullTimeout: 300

jobs:
  - script: |
      pipelineJob('test') {
        definition {
          cps {
            script("""
            pipeline {
              agent {
                label 'docker'
              }
              stages {
                stage('Hello World') {
                  steps {
                    echo 'Hello World!'
                  }
                }
              }
            }
            """)
          }
        }
      }
