apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: developer-infrastructure-as-code
spec:
  selector:
    app: docker-registry
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32001
