apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - files:
      - jcasc.yaml
    name: jcasc
secretGenerator:
  - files:
      - .secrets
    name: jcasc-secrets